TENSOR BASICS

In [2]:
import torch

x = torch.empty(1) #initializing an empty tensor of size 1 like a scalar value
print(x)
x = torch.empty(3) #initializing an empty 1d tensor of size 3 
print(x)
x = torch.empty(2,3) #initializing an empty 2d tensor  
print(x)

tensor([0.])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
#creating tensor with random values like we used to do in numpy
x = torch.rand(1) #initializing an tensor of size 1 like a scalar value
print(x)
x = torch.rand(3) #initializing an 1d tensor of size 3 
print(x)
x = torch.rand(2,3) #initializing an 2d tensor  
print(x)

tensor([0.7182])
tensor([0.1186, 0.1046, 0.5947])
tensor([[0.4426, 0.8791, 0.6107],
        [0.1566, 0.7066, 0.3705]])


In [4]:
#creating tensor with zeros or ones like we used to do in numpy
x = torch.ones(1) #initializing an tensor of size 1 like a scalar value
print(x)
x = torch.zeros(3) #initializing an 1d tensor of size 3 
print(x)
x = torch.ones(2,3) #initializing an 2d tensor  
print(x)

tensor([1.])
tensor([0., 0., 0.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
x = torch.ones(2,3) 
print(x.dtype)
#giving our tensor a specific datatype
x = torch.ones(2,3,dtype=torch.int) #similarly you can also use torch.double,torch.float16 etc 
print(x.dtype)
#checking tensor size
x = torch.ones(2,3,dtype=torch.int) #similarly you can also use torch.double,torch.float16 etc 
print(x.size()) #brackets needed because it is a function

torch.float32
torch.int32
torch.Size([2, 3])


In [11]:
# creating tensor from a list
x = torch.tensor([2,5.4])
print(x)
print(x.dtype)
print(x.size())

tensor([2.0000, 5.4000])
torch.float32
torch.Size([2])


ELEMENTWISE ADDITION OF TWO TENSORS

In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z=x+y
print(z)
z=torch.add(x,y)
print(z) 
#inplace addition
y.add_(x)  #In pytorch every function with a trailing underscore does an inplace operation
print(y)
#similary you can do sub,mul,div

tensor([[0.6160, 0.0123],
        [0.0038, 0.5647]])
tensor([[0.6633, 0.8022],
        [0.4367, 0.7818]])
tensor([[1.2793, 0.8145],
        [0.4405, 1.3465]])
tensor([[1.2793, 0.8145],
        [0.4405, 1.3465]])
tensor([[1.2793, 0.8145],
        [0.4405, 1.3465]])


SLICING

In [17]:
x = torch.rand(5,3)
print(x)
print(x[:,0])  #all the rows only the first column
print(x[1,:]) #2nd row and all the columns
print(x[1,1]) #only one element
print(x[1,1].item()) #to get the actual value of the element  when you have a tensor with only one element

tensor([[0.6557, 0.6812, 0.6755],
        [0.0482, 0.8066, 0.2419],
        [0.0941, 0.3365, 0.5502],
        [0.2944, 0.9769, 0.9492],
        [0.0114, 0.3923, 0.1037]])
tensor([0.6557, 0.0482, 0.0941, 0.2944, 0.0114])
tensor([0.0482, 0.8066, 0.2419])
tensor(0.8066)
0.8065613508224487


RESHAPING A TENSOR

In [19]:
x = torch.rand(4,4)
print(x)
y = x.view(16) #we want a 1d tensor and of course the no. of elements must be the same
print(y) 

y = x.view(-1,8) #in case of multiple dimensions if you don't want to specify one dimension you can write -1 ,pytorch automatically will take correct dimension
print(y.size())
print(y)  #2d tensor

tensor([[0.0612, 0.5988, 0.2431, 0.5597],
        [0.3423, 0.7685, 0.6997, 0.6371],
        [0.1870, 0.2019, 0.8904, 0.4938],
        [0.1297, 0.8866, 0.5496, 0.6870]])
tensor([0.0612, 0.5988, 0.2431, 0.5597, 0.3423, 0.7685, 0.6997, 0.6371, 0.1870,
        0.2019, 0.8904, 0.4938, 0.1297, 0.8866, 0.5496, 0.6870])
torch.Size([2, 8])
tensor([[0.0612, 0.5988, 0.2431, 0.5597, 0.3423, 0.7685, 0.6997, 0.6371],
        [0.1870, 0.2019, 0.8904, 0.4938, 0.1297, 0.8866, 0.5496, 0.6870]])


CONVERTING NUMPY TO A TORCH TENSOR AND VICE-VERSA

In [23]:
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy() #tensor to numpy array
print(type(b))
a.add_(1)
print(a)
print(b)

b=b+1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.])
[3. 3. 3. 3. 3.]


Now we have to be carefulabout if the tensor is in cpu not in gpu then a and b will be pointing to the same memory location so if you change in a then b will get changed. 

In [3]:
#numpy array to tensor
a = np.ones(5)
print(a)
b = torch.from_numpy(a)   # you can specify datatype here by dtype = ....
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [4]:
a += 1
print(a)
print(b) #while changing a , b will also get changed  because tensor b is in cpu and pointing to the same memory location as a

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [5]:
b.add_(1)
print(b)
print(a)

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[3. 3. 3. 3. 3.]


In [6]:
#checking if gpu is available or not
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

CREATING A GPU TENSOR

In [ ]:
#let's assume gpu is available
x = torch.ones(5,device=device) #Directly creating the tensor in the gpu
y = torch.ones(5) #at first creating the tensor in cpu 
y = y.to(device) #then moving it into gpu
z = x+y #this operation will happen in gpu and it will be much faster
# now you have to be careful because numpy can only handle a cpu tensor not a gpu tensor 
# so to convert a gpu tensor to a numpy array at first you have convert it into a cpu tensor then convert it into a numpy array
z.numpy() #it will give error
z = z.to("cpu")
g = z.numpy() # now it is a valid operation 

In [7]:
x = torch.ones(5,requires_grad=True) #by default it is false
#it will tell pytorch that when we optimize a variable that is dependent on this variable we will require the gradient w.r.t. this variable
print(x)           

tensor([1., 1., 1., 1., 1.], requires_grad=True)
